require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgrentesController do

  # This should return the minimal set of attributes required to create a valid
  # Agrente. As you add validations to Agrente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cuil" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgrentesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all agrentes as @agrentes" do
      agrente = Agrente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:agrentes).should eq([agrente])
    end
  end

  describe "GET show" do
    it "assigns the requested agrente as @agrente" do
      agrente = Agrente.create! valid_attributes
      get :show, {:id => agrente.to_param}, valid_session
      assigns(:agrente).should eq(agrente)
    end
  end

  describe "GET new" do
    it "assigns a new agrente as @agrente" do
      get :new, {}, valid_session
      assigns(:agrente).should be_a_new(Agrente)
    end
  end

  describe "GET edit" do
    it "assigns the requested agrente as @agrente" do
      agrente = Agrente.create! valid_attributes
      get :edit, {:id => agrente.to_param}, valid_session
      assigns(:agrente).should eq(agrente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Agrente" do
        expect {
          post :create, {:agrente => valid_attributes}, valid_session
        }.to change(Agrente, :count).by(1)
      end

      it "assigns a newly created agrente as @agrente" do
        post :create, {:agrente => valid_attributes}, valid_session
        assigns(:agrente).should be_a(Agrente)
        assigns(:agrente).should be_persisted
      end

      it "redirects to the created agrente" do
        post :create, {:agrente => valid_attributes}, valid_session
        response.should redirect_to(Agrente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agrente as @agrente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agrente.any_instance.stub(:save).and_return(false)
        post :create, {:agrente => { "cuil" => "invalid value" }}, valid_session
        assigns(:agrente).should be_a_new(Agrente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agrente.any_instance.stub(:save).and_return(false)
        post :create, {:agrente => { "cuil" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agrente" do
        agrente = Agrente.create! valid_attributes
        # Assuming there are no other agrentes in the database, this
        # specifies that the Agrente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Agrente.any_instance.should_receive(:update).with({ "cuil" => "MyString" })
        put :update, {:id => agrente.to_param, :agrente => { "cuil" => "MyString" }}, valid_session
      end

      it "assigns the requested agrente as @agrente" do
        agrente = Agrente.create! valid_attributes
        put :update, {:id => agrente.to_param, :agrente => valid_attributes}, valid_session
        assigns(:agrente).should eq(agrente)
      end

      it "redirects to the agrente" do
        agrente = Agrente.create! valid_attributes
        put :update, {:id => agrente.to_param, :agrente => valid_attributes}, valid_session
        response.should redirect_to(agrente)
      end
    end

    describe "with invalid params" do
      it "assigns the agrente as @agrente" do
        agrente = Agrente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agrente.any_instance.stub(:save).and_return(false)
        put :update, {:id => agrente.to_param, :agrente => { "cuil" => "invalid value" }}, valid_session
        assigns(:agrente).should eq(agrente)
      end

      it "re-renders the 'edit' template" do
        agrente = Agrente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agrente.any_instance.stub(:save).and_return(false)
        put :update, {:id => agrente.to_param, :agrente => { "cuil" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agrente" do
      agrente = Agrente.create! valid_attributes
      expect {
        delete :destroy, {:id => agrente.to_param}, valid_session
      }.to change(Agrente, :count).by(-1)
    end

    it "redirects to the agrentes list" do
      agrente = Agrente.create! valid_attributes
      delete :destroy, {:id => agrente.to_param}, valid_session
      response.should redirect_to(agrentes_url)
    end
  end

end
