require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SituacionRevistaController do

  # This should return the minimal set of attributes required to create a valid
  # SituacionRevistum. As you add validations to SituacionRevistum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "descripcion" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SituacionRevistaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all situacion_revista as @situacion_revista" do
      situacion_revistum = SituacionRevistum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:situacion_revista).should eq([situacion_revistum])
    end
  end

  describe "GET show" do
    it "assigns the requested situacion_revistum as @situacion_revistum" do
      situacion_revistum = SituacionRevistum.create! valid_attributes
      get :show, {:id => situacion_revistum.to_param}, valid_session
      assigns(:situacion_revistum).should eq(situacion_revistum)
    end
  end

  describe "GET new" do
    it "assigns a new situacion_revistum as @situacion_revistum" do
      get :new, {}, valid_session
      assigns(:situacion_revistum).should be_a_new(SituacionRevistum)
    end
  end

  describe "GET edit" do
    it "assigns the requested situacion_revistum as @situacion_revistum" do
      situacion_revistum = SituacionRevistum.create! valid_attributes
      get :edit, {:id => situacion_revistum.to_param}, valid_session
      assigns(:situacion_revistum).should eq(situacion_revistum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SituacionRevistum" do
        expect {
          post :create, {:situacion_revistum => valid_attributes}, valid_session
        }.to change(SituacionRevistum, :count).by(1)
      end

      it "assigns a newly created situacion_revistum as @situacion_revistum" do
        post :create, {:situacion_revistum => valid_attributes}, valid_session
        assigns(:situacion_revistum).should be_a(SituacionRevistum)
        assigns(:situacion_revistum).should be_persisted
      end

      it "redirects to the created situacion_revistum" do
        post :create, {:situacion_revistum => valid_attributes}, valid_session
        response.should redirect_to(SituacionRevistum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved situacion_revistum as @situacion_revistum" do
        # Trigger the behavior that occurs when invalid params are submitted
        SituacionRevistum.any_instance.stub(:save).and_return(false)
        post :create, {:situacion_revistum => { "descripcion" => "invalid value" }}, valid_session
        assigns(:situacion_revistum).should be_a_new(SituacionRevistum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SituacionRevistum.any_instance.stub(:save).and_return(false)
        post :create, {:situacion_revistum => { "descripcion" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested situacion_revistum" do
        situacion_revistum = SituacionRevistum.create! valid_attributes
        # Assuming there are no other situacion_revista in the database, this
        # specifies that the SituacionRevistum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SituacionRevistum.any_instance.should_receive(:update).with({ "descripcion" => "MyString" })
        put :update, {:id => situacion_revistum.to_param, :situacion_revistum => { "descripcion" => "MyString" }}, valid_session
      end

      it "assigns the requested situacion_revistum as @situacion_revistum" do
        situacion_revistum = SituacionRevistum.create! valid_attributes
        put :update, {:id => situacion_revistum.to_param, :situacion_revistum => valid_attributes}, valid_session
        assigns(:situacion_revistum).should eq(situacion_revistum)
      end

      it "redirects to the situacion_revistum" do
        situacion_revistum = SituacionRevistum.create! valid_attributes
        put :update, {:id => situacion_revistum.to_param, :situacion_revistum => valid_attributes}, valid_session
        response.should redirect_to(situacion_revistum)
      end
    end

    describe "with invalid params" do
      it "assigns the situacion_revistum as @situacion_revistum" do
        situacion_revistum = SituacionRevistum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SituacionRevistum.any_instance.stub(:save).and_return(false)
        put :update, {:id => situacion_revistum.to_param, :situacion_revistum => { "descripcion" => "invalid value" }}, valid_session
        assigns(:situacion_revistum).should eq(situacion_revistum)
      end

      it "re-renders the 'edit' template" do
        situacion_revistum = SituacionRevistum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SituacionRevistum.any_instance.stub(:save).and_return(false)
        put :update, {:id => situacion_revistum.to_param, :situacion_revistum => { "descripcion" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested situacion_revistum" do
      situacion_revistum = SituacionRevistum.create! valid_attributes
      expect {
        delete :destroy, {:id => situacion_revistum.to_param}, valid_session
      }.to change(SituacionRevistum, :count).by(-1)
    end

    it "redirects to the situacion_revista list" do
      situacion_revistum = SituacionRevistum.create! valid_attributes
      delete :destroy, {:id => situacion_revistum.to_param}, valid_session
      response.should redirect_to(situacion_revista_url)
    end
  end

end
