require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoContratacionsController do

  # This should return the minimal set of attributes required to create a valid
  # TipoContratacion. As you add validations to TipoContratacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "descripcion" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoContratacionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tipo_contrataciones as @tipo_contrataciones" do
      tipo_contratacion = TipoContratacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipo_contrataciones).should eq([tipo_contratacion])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_contratacion as @tipo_contratacion" do
      tipo_contratacion = TipoContratacion.create! valid_attributes
      get :show, {:id => tipo_contratacion.to_param}, valid_session
      assigns(:tipo_contratacion).should eq(tipo_contratacion)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_contratacion as @tipo_contratacion" do
      get :new, {}, valid_session
      assigns(:tipo_contratacion).should be_a_new(TipoContratacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_contratacion as @tipo_contratacion" do
      tipo_contratacion = TipoContratacion.create! valid_attributes
      get :edit, {:id => tipo_contratacion.to_param}, valid_session
      assigns(:tipo_contratacion).should eq(tipo_contratacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoContratacion" do
        expect {
          post :create, {:tipo_contratacion => valid_attributes}, valid_session
        }.to change(TipoContratacion, :count).by(1)
      end

      it "assigns a newly created tipo_contratacion as @tipo_contratacion" do
        post :create, {:tipo_contratacion => valid_attributes}, valid_session
        assigns(:tipo_contratacion).should be_a(TipoContratacion)
        assigns(:tipo_contratacion).should be_persisted
      end

      it "redirects to the created tipo_contratacion" do
        post :create, {:tipo_contratacion => valid_attributes}, valid_session
        response.should redirect_to(TipoContratacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_contratacion as @tipo_contratacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoContratacion.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_contratacion => { "descripcion" => "invalid value" }}, valid_session
        assigns(:tipo_contratacion).should be_a_new(TipoContratacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoContratacion.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_contratacion => { "descripcion" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_contratacion" do
        tipo_contratacion = TipoContratacion.create! valid_attributes
        # Assuming there are no other tipo_contrataciones in the database, this
        # specifies that the TipoContratacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TipoContratacion.any_instance.should_receive(:update).with({ "descripcion" => "MyString" })
        put :update, {:id => tipo_contratacion.to_param, :tipo_contratacion => { "descripcion" => "MyString" }}, valid_session
      end

      it "assigns the requested tipo_contratacion as @tipo_contratacion" do
        tipo_contratacion = TipoContratacion.create! valid_attributes
        put :update, {:id => tipo_contratacion.to_param, :tipo_contratacion => valid_attributes}, valid_session
        assigns(:tipo_contratacion).should eq(tipo_contratacion)
      end

      it "redirects to the tipo_contratacion" do
        tipo_contratacion = TipoContratacion.create! valid_attributes
        put :update, {:id => tipo_contratacion.to_param, :tipo_contratacion => valid_attributes}, valid_session
        response.should redirect_to(tipo_contratacion)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_contratacion as @tipo_contratacion" do
        tipo_contratacion = TipoContratacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoContratacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_contratacion.to_param, :tipo_contratacion => { "descripcion" => "invalid value" }}, valid_session
        assigns(:tipo_contratacion).should eq(tipo_contratacion)
      end

      it "re-renders the 'edit' template" do
        tipo_contratacion = TipoContratacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoContratacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_contratacion.to_param, :tipo_contratacion => { "descripcion" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_contratacion" do
      tipo_contratacion = TipoContratacion.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_contratacion.to_param}, valid_session
      }.to change(TipoContratacion, :count).by(-1)
    end

    it "redirects to the tipo_contrataciones list" do
      tipo_contratacion = TipoContratacion.create! valid_attributes
      delete :destroy, {:id => tipo_contratacion.to_param}, valid_session
      response.should redirect_to(tipo_contrataciones_url)
    end
  end

end
